### ISSUE TITLE
tomasz.napierala.org hacked?

### ISSUE THREAD

**Issue by mloskot** [zen/playground#1]
@zen  I'm opening this issue to make you aware that your website https://tomasz.napierala.org might have been hacked, so I thought you may want to check it. First, the SSL certificate does not match. Second, it loads something like Turkish news:

![image](https://github.com/zen/playground/assets/80741/76f962d4-d7ba-46da-806c-0402b9c17ed3)

**Comment by zen** [comment]
@mloskot thank you. It's my old, defunct blog CNAME pointing to non existing server that I shut down some time ago.

**Comment by mloskot** [comment]
I see. Anyway, I thought it's a good idea to let you know just in case. Cheers!
